# Generated by Django 4.0.1 on 2022-04-24 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='locations',
            new_name='locations_id',
        ),
    ]
