# Generated by Django 4.0.1 on 2022-04-24 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_locations_user_locations_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='locations_id',
            new_name='location_id',
        ),
    ]
