# Generated by Django 4.0.1 on 2022-04-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_ad_category_alter_ad_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/media/'),
        ),
    ]
