# Generated by Django 4.0.1 on 2022-05-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_ad_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('owner', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Подбор',
                'verbose_name_plural': 'Подборки',
            },
        ),
    ]
