# Generated by Django 4.0.1 on 2022-05-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_selection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selection',
            options={},
        ),
        migrations.AddField(
            model_name='selection',
            name='items',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
